spring:
  datasource:
    druid:
      #mysql
      url: jdbc:mysql://127.0.0.1:3306/athena?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: '{cipher}AQCBDuRvs2hqY/VF1IH6pR6bgbfdxSsUMi16XijtnHXaZgWSjoIidoc7/02jYVNPsYKG1dQML3G/SGA6BWxlQgQIeFsGPzv1mMGNEuplv/PPVJPccsw6qxf1DOs/VIi49hwtAn4p4Vvws4vT5Q3rnDiRL/ajnIiJAS4ovgX5HK3lAw3vOx0D/CodeWXrZuAR3Zsdkq+yn00IpW5o+qMDRLNZqAdkJFPoOWvTsOExzK87ELmdh+ktXB1+x3sAVB+dfjgORWK/LsxFP0t4WeQYhIeuXcy9jXoCV9Wuy5vOXSmtx15tVQ3u8Qxsch5B8UMzyFXbfmFTTrZygO0Qqsv9eMXvV3GpFTrJwFBYnrdWnBcMUMKBiJSP5/hH4orqUCpI+1E='
      driver-class-name: com.mysql.cj.jdbc.Driver
      
      #sqlserver
      #url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=athena
      #username: username
      #password: password
      #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      
      #oracle
      #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      #username: system
      #password: system
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      initial-size: 5    
      max-active: 20
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      validation-query: select 1
      #validation-query-timeout:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 2000
      max-evictable-idle-time-millis: 900000
      min-evictable-idle-time-millis: 600000
      filters: stat,wall,web-stat,stat-view-servlet,slf4j #配置多个英文逗号分隔

      #StatFilter配置，说明请参考Druid Wiki，配置_配置StatFilter
      stat.enabled: true
      stat.slowSqlMillis: 10000
      stat.logSlowSql: true
      stat.mergeSql: true

      # Wallfilter配置，使用缺省配置，说明请参考Druid Wiki，配置_配置Wallfilter
      wall.logViolation: true
      wall.throwException: false

      # log4jStatFilter配置
      slf4j.enabled: true
      slf4j.statement-create-after-log-enabled: false
      slf4j.statement-close-after-log-enabled: false
      slf4j.result-set-open-after-log-enabled: false
      slf4j.result-set-close-after-log-enabled: false

      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter.enabled: true #是否启用StatFilter默认值false
      web-stat-filter.url-pattern: /*
      web-stat-filter.exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      web-stat-filter.profile-enable: true

      #考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet.enabled: true #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
      stat-view-servlet.url-pattern: /druid/*
      stat-view-servlet.reset-enable: false
      stat-view-servlet.login-username: athena
      stat-view-servlet.login-password: '{cipher}AQBVBUtzwPPUz2yN6MW7IEDkJNkdGA/B3/9kxtUYFyqqur4yo8M7MxUFuPCsD7PYzJorNcgBzJaWeafOWoMnr6rBw5yspDIk8FFt2Wspdthexikc8TDnJlyJlfd0d6NWtMKBYF5YnFqu7LVROfmMd+Xg1NMWit/fe4AzXpLweSEBPrQvRyy9zcFdbC1jLajMpUXakkgJ+Va/mxMC2uQ0w+Tez6xPT7PayLUO8ODBIIgYX4XHTZC7U12Vz2c9i7VT/6YTbmALdAJwk7yE4tdcGgtOU7jH2eiC8VcryggNTv8Hfjsyva8+lIO1gkeg0cx8jGqMtooLEJ4UGckVC5FA/F+/GOMkZNAVz1u9fF7wPx2cgsmfVOBd+x59F+/P4eD5Kk8='
      #stat-view-servlet.allow:   #配置白名单
      #stat-view-servlet.deny:    #配置黑名单


#mybatis 配置 entity扫描位置
mybatis:
  typeAliasesPackage: com.athena.springboot.oauth.jwt.server.*
